FROM golang:1.22.4 as builder
RUN mkdir -p /go/src
WORKDIR /go/src
COPY . .
#RUN go work sync
RUN cd /go/src/app/viptaskapi && GOFLAGS=-mod=readonly go mod tidy
RUN cd /go/src/app/viptaskapi && CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o tiger-viptaskapi .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /go/src/app/client/cvgo-client .
COPY --from=builder /go/src/config/* /root
COPY --from=builder /go/src/config/alpha /root/internal/config
COPY --from=builder /go/src/app/client/internal/config /root/internal/config/local
COPY --from=builder /go/src/app/client/docs /root/docs

CMD ["./cvgo-client"]


