###################### 通用配置 Regoin Start ######################

# debug 为 true 会在控制台打印出每条 sql 语句
debug: true

# 默认连接
default_conn: master

# 连接池最大空闲连接数
conn_max_idle: 100

# 连接池最大连接数
conn_max_open: 5000

# 连接数最大生命周期
conn_max_lifetime: 1h

# 传输协议
protocol: tcp

# 时区
loc: Local

# 是否解析时间
parse_time: true

# 字符集
charset: utf8mb4

# 字符序
collation: utf8mb4_unicode_ci

# 连接超时
timeout: 10s

# 读超时
read_timeout: 2s

# 写超时
write_timeout: 2s

###################### 通用配置 Regoin End ######################

# 主库连接配置
master:
  driver: mysql   # 连接驱动，目前只支持 mysql
  host: 127.0.0.1
  port: 3306
  database: cvgo
  username: root
  password: "Msq123^&okK"

# 从库连接配置
#slave:
#  driver: mysql
#  host:  127.0.0.1
#  port: 3306
#  database: cvgo_slave
#  username: root
#  password: "Msq123^&okK"




