FROM golang:1.22.4 as builder
RUN mkdir -p /go/src
WORKDIR /go/src
COPY docker .
#RUN go work sync
RUN cd /go/src/app/admin && GOFLAGS=-mod=readonly go mod tidy
RUN cd /go/src/app/admin && CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o cvgo-admin .

FROM alpine:latest
RUN apk --no-cache codegen ca-certificates
WORKDIR /root
COPY --from=builder /go/src/app/admin/cvgo-admin .
COPY --from=builder /go/src/config/* /root
COPY --from=builder /go/src/config/alpha /root/internal/config
COPY --from=builder /go/src/app/admin/internal/config /root/internal/config/local
COPY --from=builder /go/src/app/admin/docs /root/docs

CMD ["./cvgo-admin"]
